// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3bhHtY7pF0NIZ0p7OJ-LLuI4ODVoRUio',
    appId: '1:993262824648:web:9e8f267158b3a75213c9fd',
    messagingSenderId: '993262824648',
    projectId: 'flutter-basics-33eb0',
    authDomain: 'flutter-basics-33eb0.firebaseapp.com',
    storageBucket: 'flutter-basics-33eb0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkdRTS38_cxo7TNFAjrSLf-RBF3fMPP5k',
    appId: '1:993262824648:android:5420d016b7bd070a13c9fd',
    messagingSenderId: '993262824648',
    projectId: 'flutter-basics-33eb0',
    storageBucket: 'flutter-basics-33eb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNR-ZFZn0rVrxKFSHaQCabk8GDGLdBbaw',
    appId: '1:993262824648:ios:68c12e056ba533fb13c9fd',
    messagingSenderId: '993262824648',
    projectId: 'flutter-basics-33eb0',
    storageBucket: 'flutter-basics-33eb0.appspot.com',
    iosBundleId: 'com.example.flutterbasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNR-ZFZn0rVrxKFSHaQCabk8GDGLdBbaw',
    appId: '1:993262824648:ios:5e268ef7fdc6597c13c9fd',
    messagingSenderId: '993262824648',
    projectId: 'flutter-basics-33eb0',
    storageBucket: 'flutter-basics-33eb0.appspot.com',
    iosBundleId: 'com.example.flutterbasics.RunnerTests',
  );
}
